#include <jni.h>
#include <dlfcn.h>
#include <string>
#include <vector>
#include <algorithm>
#include <cctype>
#include <atomic>
#include <android/log.h>
#include <unistd.h>
#include <pthread.h>
#include <errno.h>
#include <fcntl.h>

#define REDBOX_TAG "RedBoxQEMU"

#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, REDBOX_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, REDBOX_TAG, __VA_ARGS__)

static void* qemuHandle = nullptr;

typedef int (*RedBoxQemuRunFunc)(int argc, char** argv);

// QEMU ShutdownCause is generated by QAPI. In QEMU 11.1.1,
// SHUTDOWN_CAUSE_HOST_UI is enum value 5.
typedef void (*QemuSystemShutdownRequestFunc)(int reason);
static constexpr int REDBOX_SHUTDOWN_CAUSE_HOST_UI = 5;

typedef void (*QemuInputQueueBtnFunc)(
        void* console,
        int button,
        bool down
);

typedef void (*QemuInputEventSyncFunc)();
typedef void (*QemuInputEventSendKeyLinuxFunc)(
        void* console,
        unsigned int linuxKeyCode,
        bool down
);

typedef void (*QemuInputQueueRelFunc)(
        void* console,
        int axis,
        int value
);

static RedBoxQemuRunFunc redBoxQemuRun = nullptr;
static QemuSystemShutdownRequestFunc qemuSystemShutdownRequest = nullptr;

static QemuInputQueueBtnFunc qemuInputQueueBtn = nullptr;
static QemuInputEventSyncFunc qemuInputEventSync = nullptr;
static QemuInputQueueRelFunc qemuInputQueueRel = nullptr;
static QemuInputEventSendKeyLinuxFunc qemuInputEventSendKeyLinux = nullptr;

static std::atomic_bool qemuInitialized(false);
static std::atomic_bool qemuRunning(false);

static jobject redBoxDisplaySurface = nullptr;


struct RedBoxStdioCapture {
    int savedStdout = -1;
    int savedStderr = -1;
    int readFd = -1;
};

static void* redBoxStdioReader(void* opaque) {
    int fd = *static_cast<int*>(opaque);
    delete static_cast<int*>(opaque);

    char buffer[512];
    std::string pending;

    while (true) {
        ssize_t count = read(fd, buffer, sizeof(buffer));

        if (count <= 0) {
            break;
        }

        pending.append(buffer, static_cast<size_t>(count));

        size_t newlinePosition;

        while ((newlinePosition = pending.find('\n')) != std::string::npos) {
            std::string line = pending.substr(0, newlinePosition);
            pending.erase(0, newlinePosition + 1);

            if (!line.empty()) {
                __android_log_print(
                        ANDROID_LOG_ERROR,
                        "RedBoxQEMU-STDERR",
                        "%s",
                        line.c_str()
                );
            }
        }
    }

    if (!pending.empty()) {
        __android_log_print(
                ANDROID_LOG_ERROR,
                "RedBoxQEMU-STDERR",
                "%s",
                pending.c_str()
        );
    }

    close(fd);
    return nullptr;
}

static bool startQemuStdioCapture(
        RedBoxStdioCapture& capture
) {
    int pipeFds[2];

    if (pipe(pipeFds) != 0) {
        LOGE(
                "pipe() failed for QEMU stdio capture: errno=%d",
                errno
        );
        return false;
    }

    capture.savedStdout = dup(STDOUT_FILENO);
    capture.savedStderr = dup(STDERR_FILENO);

    if (capture.savedStdout < 0 ||
        capture.savedStderr < 0) {

        LOGE(
                "dup() failed for QEMU stdio capture: errno=%d",
                errno
        );

        close(pipeFds[0]);
        close(pipeFds[1]);

        if (capture.savedStdout >= 0) {
            close(capture.savedStdout);
            capture.savedStdout = -1;
        }

        if (capture.savedStderr >= 0) {
            close(capture.savedStderr);
            capture.savedStderr = -1;
        }

        return false;
    }

    if (dup2(pipeFds[1], STDOUT_FILENO) < 0 ||
        dup2(pipeFds[1], STDERR_FILENO) < 0) {

        LOGE(
                "dup2() failed for QEMU stdio capture: errno=%d",
                errno
        );

        dup2(capture.savedStdout, STDOUT_FILENO);
        dup2(capture.savedStderr, STDERR_FILENO);

        close(pipeFds[0]);
        close(pipeFds[1]);
        close(capture.savedStdout);
        close(capture.savedStderr);

        capture.savedStdout = -1;
        capture.savedStderr = -1;

        return false;
    }

    close(pipeFds[1]);

    capture.readFd = pipeFds[0];

    int* readerFd =
            new int(capture.readFd);

    pthread_t readerThread;

    int threadResult =
            pthread_create(
                    &readerThread,
                    nullptr,
                    redBoxStdioReader,
                    readerFd
            );

    if (threadResult != 0) {
        LOGE(
                "pthread_create() failed for QEMU stdio capture: %d",
                threadResult
        );

        delete readerFd;

        dup2(capture.savedStdout, STDOUT_FILENO);
        dup2(capture.savedStderr, STDERR_FILENO);

        close(capture.readFd);
        close(capture.savedStdout);
        close(capture.savedStderr);

        capture.readFd = -1;
        capture.savedStdout = -1;
        capture.savedStderr = -1;

        return false;
    }

    pthread_detach(readerThread);

    LOGI(
            "QEMU stdout/stderr capture enabled -> RedBoxQEMU-STDERR"
    );

    return true;
}

static void stopQemuStdioCapture(
        RedBoxStdioCapture& capture
) {
    fflush(stdout);
    fflush(stderr);

    if (capture.savedStdout >= 0) {
        dup2(
                capture.savedStdout,
                STDOUT_FILENO
        );

        close(capture.savedStdout);
        capture.savedStdout = -1;
    }

    if (capture.savedStderr >= 0) {
        dup2(
                capture.savedStderr,
                STDERR_FILENO
        );

        close(capture.savedStderr);
        capture.savedStderr = -1;
    }

    capture.readFd = -1;
}

static std::string jstringToString(
        JNIEnv* env,
        jstring value
) {
    if (value == nullptr) {
        return "";
    }

    const char* chars =
            env->GetStringUTFChars(
                    value,
                    nullptr
            );

    if (chars == nullptr) {
        return "";
    }

    std::string result(chars);

    env->ReleaseStringUTFChars(
            value,
            chars
    );

    return result;
}

/*
 * Split RedBox's custom QEMU parameter field into argv entries without
 * invoking a shell. Spaces separate arguments; single/double quotes preserve
 * spaces; a backslash escapes the following character.
 */
static std::vector<std::string> parseQemuParams(
        const std::string& input
) {
    std::vector<std::string> result;
    std::string current;
    bool inSingleQuote = false;
    bool inDoubleQuote = false;
    bool escaping = false;

    for (char c : input) {
        if (escaping) {
            current.push_back(c);
            escaping = false;
            continue;
        }

        if (c == '\\' && !inSingleQuote) {
            escaping = true;
            continue;
        }

        if (c == '\'' && !inDoubleQuote) {
            inSingleQuote = !inSingleQuote;
            continue;
        }

        if (c == '"' && !inSingleQuote) {
            inDoubleQuote = !inDoubleQuote;
            continue;
        }

        if (std::isspace(static_cast<unsigned char>(c)) &&
            !inSingleQuote &&
            !inDoubleQuote) {
            if (!current.empty()) {
                result.emplace_back(current);
                current.clear();
            }
            continue;
        }

        current.push_back(c);
    }

    if (escaping) {
        current.push_back('\\');
    }

    if (!current.empty()) {
        result.emplace_back(current);
    }

    return result;
}

static std::string getAppFilesDirectory(
        JNIEnv* env,
        jobject thiz
) {
    jclass activityClass =
            env->GetObjectClass(thiz);

    if (activityClass == nullptr) {
        LOGE("Could not get Activity class");
        return "";
    }

    jmethodID getFilesDirMethod =
            env->GetMethodID(
                    activityClass,
                    "getFilesDir",
                    "()Ljava/io/File;"
            );

    if (getFilesDirMethod == nullptr) {
        LOGE("Could not find Context.getFilesDir()");
        env->DeleteLocalRef(activityClass);
        return "";
    }

    jobject filesDirObject =
            env->CallObjectMethod(
                    thiz,
                    getFilesDirMethod
            );

    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
        env->DeleteLocalRef(activityClass);
        return "";
    }

    if (filesDirObject == nullptr) {
        LOGE("getFilesDir() returned null");
        env->DeleteLocalRef(activityClass);
        return "";
    }

    jclass fileClass =
            env->FindClass(
                    "java/io/File"
            );

    if (fileClass == nullptr) {
        LOGE("Could not find java.io.File");
        env->DeleteLocalRef(filesDirObject);
        env->DeleteLocalRef(activityClass);
        return "";
    }

    jmethodID getAbsolutePathMethod =
            env->GetMethodID(
                    fileClass,
                    "getAbsolutePath",
                    "()Ljava/lang/String;"
            );

    if (getAbsolutePathMethod == nullptr) {
        LOGE("Could not find File.getAbsolutePath()");
        env->DeleteLocalRef(fileClass);
        env->DeleteLocalRef(filesDirObject);
        env->DeleteLocalRef(activityClass);
        return "";
    }

    jstring pathString =
            static_cast<jstring>(
                    env->CallObjectMethod(
                            filesDirObject,
                            getAbsolutePathMethod
                    )
            );

    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
        env->DeleteLocalRef(fileClass);
        env->DeleteLocalRef(filesDirObject);
        env->DeleteLocalRef(activityClass);
        return "";
    }

    if (pathString == nullptr) {
        LOGE("getAbsolutePath() returned null");
        env->DeleteLocalRef(fileClass);
        env->DeleteLocalRef(filesDirObject);
        env->DeleteLocalRef(activityClass);
        return "";
    }

    const char* pathChars =
            env->GetStringUTFChars(
                    pathString,
                    nullptr
            );

    if (pathChars == nullptr) {
        LOGE("Could not read files directory path");
        env->DeleteLocalRef(pathString);
        env->DeleteLocalRef(fileClass);
        env->DeleteLocalRef(filesDirObject);
        env->DeleteLocalRef(activityClass);
        return "";
    }

    std::string result(pathChars);

    env->ReleaseStringUTFChars(
            pathString,
            pathChars
    );

    env->DeleteLocalRef(pathString);
    env->DeleteLocalRef(fileClass);
    env->DeleteLocalRef(filesDirObject);
    env->DeleteLocalRef(activityClass);

    return result;
}

static int openAndroidFd(
        JNIEnv* env,
        jobject thiz,
        const std::string& androidPath
) {
    if (androidPath.empty()) {
        return -1;
    }

    jclass activityClass =
            env->GetObjectClass(thiz);

    if (activityClass == nullptr) {
        LOGE("Could not obtain MainActivity class for get_fd()");
        return -1;
    }

    jmethodID getFdMethod =
            env->GetMethodID(
                    activityClass,
                    "get_fd",
                    "(Ljava/lang/String;)I"
            );

    if (getFdMethod == nullptr) {
        LOGE("Could not find MainActivity.get_fd(String)");

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }

        env->DeleteLocalRef(activityClass);
        return -1;
    }

    jstring pathString =
            env->NewStringUTF(
                    androidPath.c_str()
            );

    if (pathString == nullptr) {
        LOGE("Could not create Java string for Android file path");
        env->DeleteLocalRef(activityClass);
        return -1;
    }

    jint fd =
            env->CallIntMethod(
                    thiz,
                    getFdMethod,
                    pathString
            );

    env->DeleteLocalRef(pathString);
    env->DeleteLocalRef(activityClass);

    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
        LOGE("MainActivity.get_fd() threw an exception");
        return -1;
    }

    if (fd < 0) {
        LOGE("MainActivity.get_fd() failed");
        return -1;
    }

    LOGI(
            "Android file opened -> FD %d",
            static_cast<int>(fd)
    );

    return static_cast<int>(fd);
}

static void closeAndroidFd(
        JNIEnv* env,
        jobject thiz,
        int fd
) {
    if (fd < 0) {
        return;
    }

    jclass activityClass =
            env->GetObjectClass(thiz);

    if (activityClass == nullptr) {
        LOGE("Could not obtain MainActivity class for close_fd()");
        return;
    }

    jmethodID closeFdMethod =
            env->GetMethodID(
                    activityClass,
                    "close_fd",
                    "(I)I"
            );

    if (closeFdMethod == nullptr) {
        LOGE("Could not find MainActivity.close_fd(Int)");

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }

        env->DeleteLocalRef(activityClass);
        return;
    }

    jint result =
            env->CallIntMethod(
                    thiz,
                    closeFdMethod,
                    static_cast<jint>(fd)
            );

    env->DeleteLocalRef(activityClass);

    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
        LOGE("MainActivity.close_fd() threw an exception");
        return;
    }

    LOGI(
            "Android FD %d close result: %d",
            fd,
            static_cast<int>(result)
    );
}

static bool loadQemuEngine() {
    if (qemuHandle != nullptr) {
        return redBoxQemuRun != nullptr;
    }

    LOGI("Loading QEMU 11.1.1 engine...");

    qemuHandle =
            dlopen(
                    "libqemu-system-x86_64.so",
                    RTLD_NOW | RTLD_LOCAL
            );

    if (qemuHandle == nullptr) {
        const char* error = dlerror();

        LOGE(
                "QEMU dlopen failed: %s",
                error != nullptr
                ? error
                : "unknown error"
        );

        return false;
    }

    dlerror();

    redBoxQemuRun =
            reinterpret_cast<RedBoxQemuRunFunc>(
                    dlsym(
                            qemuHandle,
                            "redbox_qemu_run"
                    )
            );

    const char* runError = dlerror();

    if (runError != nullptr ||
        redBoxQemuRun == nullptr) {

        LOGE(
                "Could not find redbox_qemu_run: %s",
                runError != nullptr
                ? runError
                : "unknown error"
        );

        dlclose(qemuHandle);
        qemuHandle = nullptr;
        redBoxQemuRun = nullptr;

        return false;
    }

    dlerror();

    qemuInputQueueBtn =
            reinterpret_cast<QemuInputQueueBtnFunc>(
                    dlsym(
                            qemuHandle,
                            "qemu_input_queue_btn"
                    )
            );

    const char* mouseBtnError = dlerror();

    dlerror();

    qemuInputEventSync =
            reinterpret_cast<QemuInputEventSyncFunc>(
                    dlsym(
                            qemuHandle,
                            "qemu_input_event_sync"
                    )
            );

    const char* mouseSyncError = dlerror();

    dlerror();

    qemuInputQueueRel =
            reinterpret_cast<QemuInputQueueRelFunc>(
                    dlsym(
                            qemuHandle,
                            "qemu_input_queue_rel"
                    )
            );

    const char* mouseRelError = dlerror();

    dlerror();

    qemuInputEventSendKeyLinux =
            reinterpret_cast<QemuInputEventSendKeyLinuxFunc>(
                    dlsym(
                            qemuHandle,
                            "qemu_input_event_send_key_linux"
                    )
            );

    const char* keyboardError = dlerror();

    dlerror();

    qemuSystemShutdownRequest =
            reinterpret_cast<QemuSystemShutdownRequestFunc>(
                    dlsym(
                            qemuHandle,
                            "qemu_system_shutdown_request"
                    )
            );

    const char* shutdownError = dlerror();

    LOGI("QEMU 11.1.1 engine loaded");
    LOGI("redbox_qemu_run found");

    if (qemuInputQueueBtn != nullptr &&
        mouseBtnError == nullptr) {
        LOGI("qemu_input_queue_btn found");
    } else {
        LOGE(
                "qemu_input_queue_btn unavailable: %s",
                mouseBtnError != nullptr
                ? mouseBtnError
                : "symbol missing"
        );
    }

    if (qemuInputEventSync != nullptr &&
        mouseSyncError == nullptr) {
        LOGI("qemu_input_event_sync found");
    } else {
        LOGE(
                "qemu_input_event_sync unavailable: %s",
                mouseSyncError != nullptr
                ? mouseSyncError
                : "symbol missing"
        );
    }

    if (qemuInputQueueRel != nullptr &&
        mouseRelError == nullptr) {
        LOGI("qemu_input_queue_rel found");
    } else {
        LOGE(
                "qemu_input_queue_rel unavailable: %s",
                mouseRelError != nullptr
                ? mouseRelError
                : "symbol missing"
        );
    }

    if (qemuInputEventSendKeyLinux != nullptr &&
        keyboardError == nullptr) {
        LOGI("qemu_input_event_send_key_linux found");
    } else {
        LOGE(
                "qemu_input_event_send_key_linux unavailable: %s",
                keyboardError != nullptr
                ? keyboardError
                : "symbol missing"
        );
    }

    if (qemuSystemShutdownRequest != nullptr &&
        shutdownError == nullptr) {
        LOGI("qemu_system_shutdown_request found");
    } else {
        LOGE(
                "qemu_system_shutdown_request unavailable: %s",
                shutdownError != nullptr
                ? shutdownError
                : "symbol missing"
        );
    }

    return true;
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_rimvydop_redboxpcemulator_MainActivity_nativeQemuStop(
        JNIEnv* env,
        jobject thiz
) {
    (void) env;
    (void) thiz;

    if (!qemuRunning.load()) {
        LOGI("QEMU stop ignored: no VM is running");
        return JNI_TRUE;
    }

    if (!loadQemuEngine() || qemuSystemShutdownRequest == nullptr) {
        LOGE("QEMU stop failed: shutdown function unavailable");
        return JNI_FALSE;
    }

    LOGI("Requesting QEMU shutdown from RedBox UI");
    qemuSystemShutdownRequest(REDBOX_SHUTDOWN_CAUSE_HOST_UI);
    return JNI_TRUE;
}

extern "C"
JNIEXPORT void JNICALL
Java_com_rimvydop_redboxpcemulator_MainActivity_nativeSetDisplaySurface(
        JNIEnv* env,
        jobject thiz,
        jobject surface
) {
    (void) thiz;

    if (redBoxDisplaySurface != nullptr) {
        env->DeleteGlobalRef(
                redBoxDisplaySurface
        );

        redBoxDisplaySurface = nullptr;

        LOGI(
                "Previous Android display Surface released"
        );
    }

    if (surface != nullptr) {
        redBoxDisplaySurface =
                env->NewGlobalRef(
                        surface
                );

        if (redBoxDisplaySurface != nullptr) {
            LOGI(
                    "Android display Surface received by native C++"
            );
        } else {
            LOGE(
                    "Failed to create global reference for Android display Surface"
            );
        }
    } else {
        LOGI(
                "Android display Surface cleared in native C++"
        );
    }
}

/*
 * RedBox Part 2F:
 * QEMU now runs inside QemuService (:qemu).
 * Forward the service Surface call through the existing
 * MainActivity Surface implementation.
 */
extern "C"
JNIEXPORT void JNICALL
Java_com_rimvydop_redboxpcemulator_QemuService_nativeSetDisplaySurface(
        JNIEnv* env,
        jobject thiz,
        jobject surface
) {
    LOGI("QemuService nativeSetDisplaySurface() bridge called");

    Java_com_rimvydop_redboxpcemulator_MainActivity_nativeSetDisplaySurface(
            env,
            thiz,
            surface
    );
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_rimvydop_redboxpcemulator_MainActivity_nativeQemuMouseMove(
        JNIEnv* env,
        jobject thiz,
        jint deltaX,
        jint deltaY
) {
    (void) env;
    (void) thiz;

    if (!qemuRunning.load()) {
        return JNI_FALSE;
    }

    if (!loadQemuEngine()) {
        return JNI_FALSE;
    }

    if (qemuInputQueueRel == nullptr ||
        qemuInputEventSync == nullptr) {
        LOGE(
                "Mouse move ignored: QEMU relative input symbols unavailable"
        );
        return JNI_FALSE;
    }

    if (deltaX != 0) {
        qemuInputQueueRel(
                nullptr,
                0,
                static_cast<int>(deltaX)
        );
    }

    if (deltaY != 0) {
        qemuInputQueueRel(
                nullptr,
                1,
                static_cast<int>(deltaY)
        );
    }

    if (deltaX != 0 || deltaY != 0) {
        qemuInputEventSync();
    }

    return JNI_TRUE;
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_rimvydop_redboxpcemulator_MainActivity_nativeQemuMouseButton(
        JNIEnv* env,
        jobject thiz,
        jint button,
        jboolean down
) {
    (void) env;
    (void) thiz;

    if (!qemuRunning.load()) {
        LOGE("Mouse button ignored: QEMU is not running");
        return JNI_FALSE;
    }

    if (!loadQemuEngine()) {
        LOGE("Mouse button ignored: QEMU engine unavailable");
        return JNI_FALSE;
    }

    if (qemuInputQueueBtn == nullptr ||
        qemuInputEventSync == nullptr) {
        LOGE(
                "Mouse button ignored: QEMU input symbols unavailable"
        );
        return JNI_FALSE;
    }

    if (button < 0 || button > 2) {
        LOGE(
                "Mouse button ignored: invalid button %d",
                static_cast<int>(button)
        );
        return JNI_FALSE;
    }

    qemuInputQueueBtn(
            nullptr,
            static_cast<int>(button),
            down == JNI_TRUE
    );

    qemuInputEventSync();

    LOGI(
            "QEMU mouse button %d -> %s",
            static_cast<int>(button),
            down == JNI_TRUE ? "DOWN" : "UP"
    );

    return JNI_TRUE;
}

static int androidKeyCodeToLinuxKeyCode(int keyCode) {
    switch (keyCode) {
        case 7: return 11;  // 0
        case 8: return 2;   // 1
        case 9: return 3;   // 2
        case 10: return 4;  // 3
        case 11: return 5;  // 4
        case 12: return 6;  // 5
        case 13: return 7;  // 6
        case 14: return 8;  // 7
        case 15: return 9;  // 8
        case 16: return 10; // 9
        case 29: return 30; // A
        case 30: return 48; // B
        case 31: return 46; // C
        case 32: return 32; // D
        case 33: return 18; // E
        case 34: return 33; // F
        case 35: return 34; // G
        case 36: return 35; // H
        case 37: return 23; // I
        case 38: return 36; // J
        case 39: return 37; // K
        case 40: return 38; // L
        case 41: return 50; // M
        case 42: return 49; // N
        case 43: return 24; // O
        case 44: return 25; // P
        case 45: return 16; // Q
        case 46: return 19; // R
        case 47: return 31; // S
        case 48: return 20; // T
        case 49: return 22; // U
        case 50: return 47; // V
        case 51: return 17; // W
        case 52: return 45; // X
        case 53: return 21; // Y
        case 54: return 44; // Z
        case 55: return 51; // comma
        case 56: return 52; // period
        case 57: return 56; // left alt
        case 58: return 100; // right alt
        case 59: return 42; // left shift
        case 60: return 54; // right shift
        case 61: return 15; // tab
        case 62: return 57; // space
        case 66: return 28; // enter
        case 67: return 14; // backspace
        case 68: return 41; // grave
        case 69: return 12; // minus
        case 70: return 13; // equals
        case 71: return 26; // [
        case 72: return 27; // ]
        case 73: return 43; // backslash
        case 74: return 39; // semicolon
        case 75: return 40; // apostrophe
        case 76: return 53; // slash
        case 19: return 103; // up
        case 20: return 108; // down
        case 21: return 105; // left
        case 22: return 106; // right
        case 111: return 1; // escape
        case 112: return 111; // forward delete
        case 113: return 29; // left ctrl
        case 114: return 97; // right ctrl
        case 115: return 58; // caps lock
        case 122: return 102; // home
        case 123: return 107; // end
        case 124: return 110; // insert
        case 92: return 104; // page up
        case 93: return 109; // page down
        case 131: return 59; // F1
        case 132: return 60; // F2
        case 133: return 61; // F3
        case 134: return 62; // F4
        case 135: return 63; // F5
        case 136: return 64; // F6
        case 137: return 65; // F7
        case 138: return 66; // F8
        case 139: return 67; // F9
        case 140: return 68; // F10
        case 141: return 87; // F11
        case 142: return 88; // F12
        default: return -1;
    }
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_rimvydop_redboxpcemulator_MainActivity_nativeQemuKeyboardKey(
        JNIEnv* env,
        jobject thiz,
        jint androidKeyCode,
        jboolean down
) {
    (void) env;
    (void) thiz;

    if (!qemuRunning.load() || !loadQemuEngine()) {
        return JNI_FALSE;
    }

    if (qemuInputEventSendKeyLinux == nullptr) {
        LOGE("Keyboard input unavailable: QEMU Linux-key input symbol missing");
        return JNI_FALSE;
    }

    const int linuxKeyCode =
            androidKeyCodeToLinuxKeyCode(
                    static_cast<int>(androidKeyCode)
            );

    if (linuxKeyCode < 0) {
        LOGE(
                "Ignoring unsupported Android keyboard key code: %d",
                static_cast<int>(androidKeyCode)
        );
        return JNI_FALSE;
    }

    qemuInputEventSendKeyLinux(
            nullptr,
            static_cast<unsigned int>(linuxKeyCode),
            down == JNI_TRUE
    );

    return JNI_TRUE;
}

extern "C"
JNIEXPORT jstring JNICALL
Java_com_rimvydop_redboxpcemulator_MainActivity_nativeQemuStatus(
        JNIEnv* env,
        jobject thiz
) {
    (void) thiz;

    if (!loadQemuEngine()) {
        return env->NewStringUTF(
                "QEMU 11.1.1 Load Failed"
        );
    }

    if (qemuRunning.load()) {
        return env->NewStringUTF(
                "QEMU 11.1.1 Engine Running"
        );
    }

    if (qemuInitialized.load()) {
        return env->NewStringUTF(
                "QEMU 11.1.1 Engine Initialized"
        );
    }

    return env->NewStringUTF(
            "QEMU 11.1.1 Engine Loaded Successfully"
    );
}

extern "C"
JNIEXPORT jstring JNICALL
Java_com_rimvydop_redboxpcemulator_MainActivity_nativeQemuStart(
        JNIEnv* env,
        jobject thiz,
        jint ramMb,
        jint cpuCores,
        jstring diskUriJava,
        jstring diskImageNameJava,
        jstring isoUriJava,
        jstring driverIsoUriJava,
        jstring sharedDiskUriJava,
        jstring sharedDiskImageNameJava,
        jboolean sharedFolderEnabledJava,
        jstring cpuModelJava,
        jstring cpuFlagsJava,
        jint tcgCacheMb,
        jboolean multiThreadedTcg,
        jstring machineTypeJava,
        jstring diskInterfaceJava,
        jstring displayAdapterJava,
        jboolean networkEnabledJava,
        jstring networkAdapterJava,
        jstring networkModeJava,
        jstring qemuParamsJava,
        jstring biosDateJava,
        jstring soundCardJava
) {
    LOGI("=================================");
    LOGI("RedBox QEMU 11.1.1 SDL WINDOWS + ISO TEST");
    LOGI("Android fd-set + VHD + AHCI + optional ISO CD-ROM");
    LOGI("=================================");

    if (!loadQemuEngine()) {
        return env->NewStringUTF(
                "QEMU Disk Test Failed: engine could not be loaded"
        );
    }

    if (qemuRunning.load()) {
        return env->NewStringUTF(
                "QEMU Engine Already Running"
        );
    }

    if (qemuInitialized.load()) {
        return env->NewStringUTF(
                "QEMU Engine Already Initialized"
        );
    }

    std::string diskUri =
            jstringToString(
                    env,
                    diskUriJava
            );

    std::string diskImageName =
            jstringToString(
                    env,
                    diskImageNameJava
            );

    std::string isoUri =
            jstringToString(
                    env,
                    isoUriJava
            );

    std::string driverIsoUri =
            jstringToString(
                    env,
                    driverIsoUriJava
            );

    std::string sharedDiskUri =
            jstringToString(
                    env,
                    sharedDiskUriJava
            );

    std::string sharedDiskImageName =
            jstringToString(
                    env,
                    sharedDiskImageNameJava
            );

    const bool sharedFolderEnabled =
            sharedFolderEnabledJava == JNI_TRUE;

    std::string cpuModel =
            jstringToString(
                    env,
                    cpuModelJava
            );

    std::string cpuFlags =
            jstringToString(
                    env,
                    cpuFlagsJava
            );

    std::string machineType =
            jstringToString(
                    env,
                    machineTypeJava
            );

    std::string diskInterface =
            jstringToString(
                    env,
                    diskInterfaceJava
            );

    std::string displayAdapter =
            jstringToString(
                    env,
                    displayAdapterJava
            );

    const bool networkEnabled =
            networkEnabledJava == JNI_TRUE;

    std::string networkAdapter =
            jstringToString(
                    env,
                    networkAdapterJava
            );

    std::string networkMode =
            jstringToString(
                    env,
                    networkModeJava
            );

    std::string qemuParams =
            jstringToString(
                    env,
                    qemuParamsJava
            );

    std::string biosDate =
            jstringToString(
                    env,
                    biosDateJava
            );

    std::string soundCard =
            jstringToString(
                    env,
                    soundCardJava
            );

    if (soundCard != "Intel HDA" &&
        soundCard != "AC97" &&
        soundCard != "Sound Blaster 16") {
        soundCard = "Intel HDA";
    }

    if (networkAdapter != "Realtek RTL8139" &&
        networkAdapter != "Intel E1000" &&
        networkAdapter != "Intel E1000E" &&
        networkAdapter != "AMD PCnet") {
        networkAdapter = "Intel E1000";
    }

    if (networkMode != "User (NAT)") {
        networkMode = "User (NAT)";
    }

    if (displayAdapter != "Bochs Display" &&
        displayAdapter != "VirtIO VGA" &&
        displayAdapter != "Cirrus VGA") {
        displayAdapter = "Standard VGA";
    }

    if (diskInterface == "VirtIO Block") {
        // Compatibility with VMs saved by an earlier RedBox build.
        diskInterface = "VirtIO Block";
    }

    if (diskInterface != "IDE" &&
        diskInterface != "VirtIO Block") {
        diskInterface = "AHCI";
    }

    if (cpuModel != "qemu64" &&
        cpuModel != "core2duo" &&
        cpuModel != "Nehalem" &&
        cpuModel != "SandyBridge" &&
        cpuModel != "Haswell" &&
        cpuModel != "max") {
        cpuModel = "Default";
    }

    if (machineType != "q35") {
        machineType = "pc";
    }

    // Our legacy IDE attachment uses the PC/i440FX IDE buses.
    // Keep this safe even if an older saved VM somehow contains Q35 + IDE.
    if (diskInterface == "IDE" && machineType == "q35") {
        LOGI("IDE selected with Q35; falling back to machine=pc");
        machineType = "pc";
    }

    int safeTcgCacheMb =
            static_cast<int>(tcgCacheMb);

    if (safeTcgCacheMb != 128 &&
        safeTcgCacheMb != 256 &&
        safeTcgCacheMb != 512) {
        safeTcgCacheMb = 256;
    }

    const bool useMultiThreadedTcg =
            multiThreadedTcg == JNI_TRUE;

    // CPU flags are stored as comma-separated names and validated here.
    const std::vector<std::string> allowedCpuFlags = {
            "sse3",
            "ssse3",
            "sse4.1",
            "sse4.2",
            "popcnt",
            "aes",
            "avx"
    };

    std::vector<std::string> enabledCpuFlags;
    std::string currentCpuFlag;

    auto appendCpuFlagIfAllowed = [&]() {
        if (currentCpuFlag.empty()) {
            return;
        }

        currentCpuFlag.erase(
                std::remove_if(
                        currentCpuFlag.begin(),
                        currentCpuFlag.end(),
                        [](unsigned char c) { return std::isspace(c); }
                ),
                currentCpuFlag.end()
        );

        if (std::find(
                allowedCpuFlags.begin(),
                allowedCpuFlags.end(),
                currentCpuFlag
        ) != allowedCpuFlags.end()) {
            enabledCpuFlags.emplace_back(currentCpuFlag);
        } else {
            LOGE("Ignoring unsupported CPU flag: %s", currentCpuFlag.c_str());
        }

        currentCpuFlag.clear();
    };

    for (char c : cpuFlags) {
        if (c == ',') {
            appendCpuFlagIfAllowed();
        } else {
            currentCpuFlag.push_back(c);
        }
    }
    appendCpuFlagIfAllowed();

    LOGI(
            "Performance: cpu=%s, tcg-cache=%dMB, mtTCG=%s, machine=%s, disk=%s, display=%s",
            cpuModel.c_str(),
            safeTcgCacheMb,
            useMultiThreadedTcg ? "on" : "off",
            machineType.c_str(),
            diskInterface.c_str(),
            displayAdapter.c_str()
    );

    LOGI(
            "Network: enabled=%s, adapter=%s, mode=%s",
            networkEnabled ? "yes" : "no",
            networkAdapter.c_str(),
            networkMode.c_str()
    );

    if (diskUri.empty()) {
        return env->NewStringUTF(
                "QEMU Disk Test Failed: no disk image selected"
        );
    }

    /*
     * Select the QEMU block format from the user-visible filename.
     *
     * RedBox previously hardcoded format=vpc for every disk. That is correct
     * for .vhd files, but a .qcow2 file must be opened with format=qcow2.
     * Passing a QCOW2 image to the VPC driver can make QEMU fail during VM
     * startup.
     */
    std::string lowerDiskName = diskImageName;

    std::transform(
            lowerDiskName.begin(),
            lowerDiskName.end(),
            lowerDiskName.begin(),
            [](unsigned char c) {
                return static_cast<char>(std::tolower(c));
            }
    );

    std::string diskFormat;

    if (lowerDiskName.size() >= 6 &&
        lowerDiskName.compare(
                lowerDiskName.size() - 6,
                6,
                ".qcow2"
        ) == 0) {
        diskFormat = "qcow2";
    } else if (lowerDiskName.size() >= 5 &&
               lowerDiskName.compare(
                       lowerDiskName.size() - 5,
                       5,
                       ".qcow"
               ) == 0) {
        diskFormat = "qcow";
    } else if (lowerDiskName.size() >= 4 &&
               lowerDiskName.compare(
                       lowerDiskName.size() - 4,
                       4,
                       ".vdi"
               ) == 0) {
        diskFormat = "vdi";
    } else if (
            (lowerDiskName.size() >= 4 &&
             lowerDiskName.compare(
                     lowerDiskName.size() - 4,
                     4,
                     ".vhd"
             ) == 0) ||
            (lowerDiskName.size() >= 4 &&
             lowerDiskName.compare(
                     lowerDiskName.size() - 4,
                     4,
                     ".vpc"
             ) == 0)
            ) {
        diskFormat = "vpc";
    } else if (
            (lowerDiskName.size() >= 4 &&
             lowerDiskName.compare(
                     lowerDiskName.size() - 4,
                     4,
                     ".img"
             ) == 0) ||
            (lowerDiskName.size() >= 4 &&
             lowerDiskName.compare(
                     lowerDiskName.size() - 4,
                     4,
                     ".raw"
             ) == 0)
            ) {
        diskFormat = "raw";
    } else {
        /*
         * Keep the old RedBox behaviour for unknown extensions rather than
         * silently enabling QEMU format probing for writable disks.
         */
        diskFormat = "vpc";
    }

    LOGI(
            "Disk image: name=%s, format=%s",
            diskImageName.c_str(),
            diskFormat.c_str()
    );

    std::string sharedDiskFormat;

    if (!sharedDiskUri.empty()) {
        std::string lowerSharedDiskName = sharedDiskImageName;

        std::transform(
                lowerSharedDiskName.begin(),
                lowerSharedDiskName.end(),
                lowerSharedDiskName.begin(),
                [](unsigned char c) {
                    return static_cast<char>(std::tolower(c));
                }
        );

        if (lowerSharedDiskName.size() >= 6 &&
            lowerSharedDiskName.compare(lowerSharedDiskName.size() - 6, 6, ".qcow2") == 0) {
            sharedDiskFormat = "qcow2";
        } else if (lowerSharedDiskName.size() >= 5 &&
                   lowerSharedDiskName.compare(lowerSharedDiskName.size() - 5, 5, ".qcow") == 0) {
            sharedDiskFormat = "qcow";
        } else if (lowerSharedDiskName.size() >= 4 &&
                   lowerSharedDiskName.compare(lowerSharedDiskName.size() - 4, 4, ".vdi") == 0) {
            sharedDiskFormat = "vdi";
        } else if ((lowerSharedDiskName.size() >= 4 &&
                    lowerSharedDiskName.compare(lowerSharedDiskName.size() - 4, 4, ".vhd") == 0) ||
                   (lowerSharedDiskName.size() >= 4 &&
                    lowerSharedDiskName.compare(lowerSharedDiskName.size() - 4, 4, ".vpc") == 0)) {
            sharedDiskFormat = "vpc";
        } else if ((lowerSharedDiskName.size() >= 4 &&
                    lowerSharedDiskName.compare(lowerSharedDiskName.size() - 4, 4, ".img") == 0) ||
                   (lowerSharedDiskName.size() >= 4 &&
                    lowerSharedDiskName.compare(lowerSharedDiskName.size() - 4, 4, ".raw") == 0)) {
            sharedDiskFormat = "raw";
        } else {
            sharedDiskFormat = "raw";
        }

        LOGI(
                "Shared disk: name=%s, format=%s",
                sharedDiskImageName.c_str(),
                sharedDiskFormat.c_str()
        );
    }

    std::string appFilesDirectory =
            getAppFilesDirectory(
                    env,
                    thiz
            );

    if (appFilesDirectory.empty()) {
        return env->NewStringUTF(
                "QEMU Disk Test Failed: application directory unavailable"
        );
    }

    const std::string sharedFolderPath =
            appFilesDirectory + "/redbox_shared";

    if (sharedFolderEnabled) {
        LOGI("Shared Folder Part 2 enabled -> %s", sharedFolderPath.c_str());
    }

    jclass activityClass =
            env->GetObjectClass(thiz);

    if (activityClass == nullptr) {
        return env->NewStringUTF(
                "QEMU Disk Test Failed: activity class unavailable"
        );
    }

    jmethodID prepareFirmwareMethod =
            env->GetMethodID(
                    activityClass,
                    "prepareQemuFirmware",
                    "()Z"
            );

    if (prepareFirmwareMethod == nullptr) {
        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }

        env->DeleteLocalRef(activityClass);

        return env->NewStringUTF(
                "QEMU Disk Test Failed: firmware preparation method missing"
        );
    }

    jboolean firmwareReady =
            env->CallBooleanMethod(
                    thiz,
                    prepareFirmwareMethod
            );

    env->DeleteLocalRef(activityClass);

    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();

        return env->NewStringUTF(
                "QEMU Disk Test Failed: firmware preparation exception"
        );
    }

    if (firmwareReady != JNI_TRUE) {
        return env->NewStringUTF(
                "QEMU Disk Test Failed: firmware preparation failed"
        );
    }

    LOGI("QEMU firmware is ready");

    int diskFd =
            openAndroidFd(
                    env,
                    thiz,
                    diskUri
            );

    if (diskFd < 0) {
        return env->NewStringUTF(
                "QEMU Disk Test Failed: could not open disk image"
        );
    }

    /*
     * Android SAF gives RedBox a writable O_RDWR descriptor.
     *
     * RedBox's Android-specific QEMU patch allows that O_RDWR descriptor
     * to satisfy a block-layer O_RDONLY fd-set request as well. Therefore
     * we only need one private descriptor for QEMU.
     *
     * Keep the Java-owned diskFd open until QEMU eventually returns.
     */

    int qemuRwFd =
            dup(diskFd);

    if (qemuRwFd < 0) {
        closeAndroidFd(
                env,
                thiz,
                diskFd
        );

        return env->NewStringUTF(
                "QEMU Disk Test Failed: could not duplicate Android fd"
        );
    }

    int fdFlags =
            fcntl(
                    qemuRwFd,
                    F_GETFD
            );

    if (fdFlags < 0 ||
        fcntl(
                qemuRwFd,
                F_SETFD,
                fdFlags & ~FD_CLOEXEC
        ) < 0) {

        close(qemuRwFd);

        closeAndroidFd(
                env,
                thiz,
                diskFd
        );

        return env->NewStringUTF(
                "QEMU Disk Test Failed: could not clear FD_CLOEXEC"
        );
    }

    int rwStatusFlags =
            fcntl(
                    qemuRwFd,
                    F_GETFL
            );

    LOGI(
            "Android Java fd=%d, QEMU inherited fd=%d flags=0x%x, FD_CLOEXEC cleared",
            diskFd,
            qemuRwFd,
            rwStatusFlags
    );

    /*
     * Optional CD-ROM / ISO.
     *
     * Keep the Java-owned descriptor open while QEMU is running, and pass
     * QEMU its own duplicate through fd-set 2. The ISO remains read-only.
     */
    int isoFd = -1;
    int qemuIsoFd = -1;

    if (!isoUri.empty()) {
        isoFd =
                openAndroidFd(
                        env,
                        thiz,
                        isoUri
                );

        if (isoFd < 0) {
            close(qemuRwFd);

            closeAndroidFd(
                    env,
                    thiz,
                    diskFd
            );

            return env->NewStringUTF(
                    "QEMU ISO Test Failed: could not open ISO image"
            );
        }

        qemuIsoFd = dup(isoFd);

        if (qemuIsoFd < 0) {
            closeAndroidFd(
                    env,
                    thiz,
                    isoFd
            );

            close(qemuRwFd);

            closeAndroidFd(
                    env,
                    thiz,
                    diskFd
            );

            return env->NewStringUTF(
                    "QEMU ISO Test Failed: could not duplicate ISO fd"
            );
        }

        int isoFdFlags =
                fcntl(
                        qemuIsoFd,
                        F_GETFD
                );

        if (isoFdFlags < 0 ||
            fcntl(
                    qemuIsoFd,
                    F_SETFD,
                    isoFdFlags & ~FD_CLOEXEC
            ) < 0) {

            close(qemuIsoFd);

            closeAndroidFd(
                    env,
                    thiz,
                    isoFd
            );

            close(qemuRwFd);

            closeAndroidFd(
                    env,
                    thiz,
                    diskFd
            );

            return env->NewStringUTF(
                    "QEMU ISO Test Failed: could not clear ISO FD_CLOEXEC"
            );
        }

        int isoStatusFlags =
                fcntl(
                        qemuIsoFd,
                        F_GETFL
                );

        LOGI(
                "ISO Java fd=%d, QEMU inherited fd=%d flags=0x%x, FD_CLOEXEC cleared",
                isoFd,
                qemuIsoFd,
                isoStatusFlags
        );
    } else {
        LOGI("No ISO selected; booting without CD-ROM media");
    }

    /* Optional second virtual hard disk used as RedBox shared storage. */
    int sharedDiskFd = -1;
    int qemuSharedDiskFd = -1;

    if (!sharedDiskUri.empty()) {
        sharedDiskFd = openAndroidFd(env, thiz, sharedDiskUri);

        if (sharedDiskFd < 0) {
            if (qemuIsoFd >= 0) {
                close(qemuIsoFd);
            }
            if (isoFd >= 0) {
                closeAndroidFd(env, thiz, isoFd);
            }
            close(qemuRwFd);
            closeAndroidFd(env, thiz, diskFd);
            return env->NewStringUTF(
                    "QEMU Shared Drive Failed: could not open shared disk image"
            );
        }

        qemuSharedDiskFd = dup(sharedDiskFd);

        if (qemuSharedDiskFd < 0) {
            closeAndroidFd(env, thiz, sharedDiskFd);
            if (qemuIsoFd >= 0) {
                close(qemuIsoFd);
            }
            if (isoFd >= 0) {
                closeAndroidFd(env, thiz, isoFd);
            }
            close(qemuRwFd);
            closeAndroidFd(env, thiz, diskFd);
            return env->NewStringUTF(
                    "QEMU Shared Drive Failed: could not duplicate shared disk fd"
            );
        }

        int sharedFdFlags = fcntl(qemuSharedDiskFd, F_GETFD);
        if (sharedFdFlags < 0 ||
            fcntl(qemuSharedDiskFd, F_SETFD, sharedFdFlags & ~FD_CLOEXEC) < 0) {
            close(qemuSharedDiskFd);
            closeAndroidFd(env, thiz, sharedDiskFd);
            if (qemuIsoFd >= 0) {
                close(qemuIsoFd);
            }
            if (isoFd >= 0) {
                closeAndroidFd(env, thiz, isoFd);
            }
            close(qemuRwFd);
            closeAndroidFd(env, thiz, diskFd);
            return env->NewStringUTF(
                    "QEMU Shared Drive Failed: could not clear shared disk FD_CLOEXEC"
            );
        }

        LOGI(
                "Shared disk Java fd=%d, QEMU inherited fd=%d",
                sharedDiskFd,
                qemuSharedDiskFd
        );
    } else {
        LOGI("No shared disk selected");
    }

    /*
     * Optional CD-ROM 2 / driver ISO.
     * fd-set 4 is reserved for this optical disc.
     */
    int driverIsoFd = -1;
    int qemuDriverIsoFd = -1;

    if (!driverIsoUri.empty()) {
        driverIsoFd = openAndroidFd(env, thiz, driverIsoUri);

        if (driverIsoFd < 0) {
            if (qemuSharedDiskFd >= 0) close(qemuSharedDiskFd);
            if (sharedDiskFd >= 0) closeAndroidFd(env, thiz, sharedDiskFd);
            if (qemuIsoFd >= 0) close(qemuIsoFd);
            if (isoFd >= 0) closeAndroidFd(env, thiz, isoFd);
            close(qemuRwFd);
            closeAndroidFd(env, thiz, diskFd);
            return env->NewStringUTF(
                    "QEMU Driver ISO Failed: could not open CD-ROM 2 image"
            );
        }

        qemuDriverIsoFd = dup(driverIsoFd);

        if (qemuDriverIsoFd < 0) {
            closeAndroidFd(env, thiz, driverIsoFd);
            if (qemuSharedDiskFd >= 0) close(qemuSharedDiskFd);
            if (sharedDiskFd >= 0) closeAndroidFd(env, thiz, sharedDiskFd);
            if (qemuIsoFd >= 0) close(qemuIsoFd);
            if (isoFd >= 0) closeAndroidFd(env, thiz, isoFd);
            close(qemuRwFd);
            closeAndroidFd(env, thiz, diskFd);
            return env->NewStringUTF(
                    "QEMU Driver ISO Failed: could not duplicate CD-ROM 2 fd"
            );
        }

        int driverIsoFdFlags = fcntl(qemuDriverIsoFd, F_GETFD);
        if (driverIsoFdFlags < 0 ||
            fcntl(qemuDriverIsoFd, F_SETFD,
                  driverIsoFdFlags & ~FD_CLOEXEC) < 0) {
            close(qemuDriverIsoFd);
            closeAndroidFd(env, thiz, driverIsoFd);
            if (qemuSharedDiskFd >= 0) close(qemuSharedDiskFd);
            if (sharedDiskFd >= 0) closeAndroidFd(env, thiz, sharedDiskFd);
            if (qemuIsoFd >= 0) close(qemuIsoFd);
            if (isoFd >= 0) closeAndroidFd(env, thiz, isoFd);
            close(qemuRwFd);
            closeAndroidFd(env, thiz, diskFd);
            return env->NewStringUTF(
                    "QEMU Driver ISO Failed: could not clear CD-ROM 2 FD_CLOEXEC"
            );
        }

        LOGI(
                "Driver ISO Java fd=%d, QEMU inherited fd=%d",
                driverIsoFd,
                qemuDriverIsoFd
        );
    } else {
        LOGI("No CD-ROM 2 / driver ISO selected");
    }

    std::vector<std::string> arguments;

    arguments.emplace_back("qemu-system-x86_64");

    arguments.emplace_back("-L");
    arguments.emplace_back(appFilesDirectory);

    /*
     * Graphics Part 5C:
     * VirtIO VGA uses QEMU's VirGL/OpenGL device and SDL's OpenGL ES path.
     * All other adapters stay on the known-good SDL 2D path.
     */
    const bool useVirglGraphics =
            displayAdapter == "VirtIO VGA";

    arguments.emplace_back("-display");
    arguments.emplace_back(
            useVirglGraphics
            ? "sdl,gl=es"
            : "sdl,gl=off"
    );

    LOGI(
            "Graphics Part 5C: adapter=%s, SDL GL=%s",
            displayAdapter.c_str(),
            useVirglGraphics ? "OpenGL ES" : "off"
    );

    arguments.emplace_back("-monitor");
    arguments.emplace_back("none");

    arguments.emplace_back("-nodefaults");

    arguments.emplace_back("-machine");
    arguments.emplace_back(machineType);

    /*
     * -nodefaults removes QEMU's automatic display adapter.
     * Add the selected emulated graphics device explicitly.
     *
     * Standard VGA and Cirrus use QEMU's -vga option.
     * Bochs and VirtIO VGA are explicit PCI devices.
     */
    if (displayAdapter == "Bochs Display") {
        arguments.emplace_back("-device");
        arguments.emplace_back("bochs-display");
    } else if (displayAdapter == "VirtIO VGA") {
        /*
         * GL-enabled VirtIO VGA. This activates QEMU's virglrenderer path.
         * The non-GL virtio-vga device is intentionally not used here so
         * this selection becomes RedBox's first real VirGL runtime test.
         */
        arguments.emplace_back("-device");
        arguments.emplace_back("virtio-vga-gl");
    } else if (displayAdapter == "Cirrus VGA") {
        arguments.emplace_back("-vga");
        arguments.emplace_back("cirrus");
    } else {
        arguments.emplace_back("-vga");
        arguments.emplace_back("std");
    }

    arguments.emplace_back("-m");
    arguments.emplace_back(
            std::to_string(
                    ramMb > 0 ? static_cast<int>(ramMb) : 512
            )
    );

    arguments.emplace_back("-smp");
    arguments.emplace_back(
            std::to_string(
                    cpuCores > 0 ? static_cast<int>(cpuCores) : 1
            )
    );

    if (cpuModel != "Default" || !enabledCpuFlags.empty()) {
        std::string cpuArgument =
                cpuModel != "Default"
                ? cpuModel
                : "qemu64";

        for (const std::string& flag : enabledCpuFlags) {
            cpuArgument += ",+" + flag;
        }

        arguments.emplace_back("-cpu");
        arguments.emplace_back(cpuArgument);

        LOGI("CPU argument: %s", cpuArgument.c_str());
    }

    std::string tcgArgument =
            std::string("tcg,thread=") +
            (useMultiThreadedTcg ? "multi" : "single") +
            ",tb-size=" +
            std::to_string(safeTcgCacheMb);

    arguments.emplace_back("-accel");
    arguments.emplace_back(tcgArgument);

    /*
     * Network Part 2:
     * QEMU user-mode networking (SLIRP/NAT) requires no root or TAP device.
     * Give the backend a stable id, then attach the selected emulated PCI NIC.
     */
    if (networkEnabled) {
        arguments.emplace_back("-netdev");
        arguments.emplace_back("user,id=redboxnet0");

        arguments.emplace_back("-device");

        if (networkAdapter == "Realtek RTL8139") {
            arguments.emplace_back("rtl8139,netdev=redboxnet0");
        } else if (networkAdapter == "AMD PCnet") {
            arguments.emplace_back("pcnet,netdev=redboxnet0");
        } else if (networkAdapter == "Intel E1000E") {
            arguments.emplace_back("e1000e,netdev=redboxnet0");
        } else {
            arguments.emplace_back("e1000,netdev=redboxnet0");
        }
    }

    /*
     * Audio Part 2:
     * Keep RedBox's SDL audio backend and allow the VM to choose its
     * emulated sound hardware.
     */
    arguments.emplace_back("-audiodev");
    arguments.emplace_back("sdl,id=redboxaudio");

    if (soundCard == "AC97") {
        arguments.emplace_back("-device");
        arguments.emplace_back("AC97,audiodev=redboxaudio");
    } else if (soundCard == "Sound Blaster 16") {
        arguments.emplace_back("-device");
        arguments.emplace_back("sb16,audiodev=redboxaudio");
    } else {
        arguments.emplace_back("-device");
        arguments.emplace_back("intel-hda");

        arguments.emplace_back("-device");
        arguments.emplace_back("hda-duplex,audiodev=redboxaudio");
    }

    /*
     * Put the Android O_RDWR descriptor into QEMU fd-set 1.
     *
     * The RedBox Android QEMU patch permits this descriptor to satisfy
     * an O_RDONLY request while preserving normal matching elsewhere.
     */
    std::string addFdArgument =
            "fd=" +
            std::to_string(qemuRwFd) +
            ",set=1,opaque=redboxdisk";

    arguments.emplace_back("-add-fd");
    arguments.emplace_back(addFdArgument);

    if (qemuIsoFd >= 0) {
        std::string addIsoFdArgument =
                "fd=" +
                std::to_string(qemuIsoFd) +
                ",set=2,opaque=redboxiso";

        arguments.emplace_back("-add-fd");
        arguments.emplace_back(addIsoFdArgument);
    }

    if (qemuSharedDiskFd >= 0) {
        std::string addSharedDiskFdArgument =
                "fd=" +
                std::to_string(qemuSharedDiskFd) +
                ",set=3,opaque=redboxshared";

        arguments.emplace_back("-add-fd");
        arguments.emplace_back(addSharedDiskFdArgument);
    }

    if (qemuDriverIsoFd >= 0) {
        std::string addDriverIsoFdArgument =
                "fd=" +
                std::to_string(qemuDriverIsoFd) +
                ",set=4,opaque=redboxdriveriso";

        arguments.emplace_back("-add-fd");
        arguments.emplace_back(addDriverIsoFdArgument);
    }

    /*
     * Attach the validated Android VHD to an emulated AHCI controller.
     *
     * QEMU 11.1.1 now uses its SDL2 2D display backend. The SDL2 library
     * is the same Android-patched Limbo/RedBox SDL2 runtime already used by
     * the app, so the guest framebuffer can flow into the existing
     * ExSDLSurface path without changing MainActivity or VMDisplay.
     */
    // AHCI needs an emulated ICH9 SATA controller.
    // VirtIO uses virtio-blk-pci for the main disk. If an ISO is mounted
    // while VirtIO Block is selected, keep a small AHCI controller only for the
    // virtual CD-ROM so Windows installers/driver ISOs continue to work.
    const bool needsAhciController =
            diskInterface == "AHCI" ||
            (diskInterface == "VirtIO Block" &&
             (qemuIsoFd >= 0 || qemuDriverIsoFd >= 0 || qemuSharedDiskFd >= 0 || sharedFolderEnabled));

    if (needsAhciController) {
        arguments.emplace_back("-device");
        arguments.emplace_back("ich9-ahci,id=ahci");
    }

    std::string diskDriveArgument =
            "file=/dev/fdset/1,if=none,id=redboxdisk,format=" +
            diskFormat;

    arguments.emplace_back("-drive");
    arguments.emplace_back(diskDriveArgument);

    arguments.emplace_back("-device");

    if (diskInterface == "IDE") {
        arguments.emplace_back(
                "ide-hd,drive=redboxdisk,bus=ide.0,bootindex=1"
        );
    } else if (diskInterface == "VirtIO Block") {
        arguments.emplace_back(
                "virtio-blk-pci,drive=redboxdisk,bootindex=1"
        );
    } else {
        arguments.emplace_back(
                "ide-hd,drive=redboxdisk,bus=ahci.0,bootindex=1"
        );
    }

    /*
     * Shared Storage Part 1: expose the selected image as a second writable
     * hard disk. Windows sees it like another physical drive.
     */
    if (qemuSharedDiskFd >= 0) {
        std::string sharedDriveArgument =
                "file=/dev/fdset/3,if=none,id=redboxshared,format=" +
                sharedDiskFormat;

        arguments.emplace_back("-drive");
        arguments.emplace_back(sharedDriveArgument);
        arguments.emplace_back("-device");

        if (diskInterface == "IDE") {
            arguments.emplace_back(
                    "ide-hd,drive=redboxshared,bus=ide.0,unit=1"
            );
        } else if (diskInterface == "VirtIO Block") {
            arguments.emplace_back(
                    "ide-hd,drive=redboxshared,bus=ahci.2"
            );
        } else {
            arguments.emplace_back(
                    "ide-hd,drive=redboxshared,bus=ahci.2"
            );
        }
    }

    /*
     * Shared Storage Part 2:
     * QEMU VVFAT exposes RedBox's private redbox_shared directory as a
     * Windows-readable FAT hard disk. Files selected through Android SAF are
     * copied into that directory by MainActivity/CreateVM before QEMU starts.
     *
     * A manually selected Shared Hard Drive takes priority if both are set.
     */
    if (sharedFolderEnabled && qemuSharedDiskFd < 0) {
        std::string sharedFolderDriveArgument =
                "file=fat:rw:" + sharedFolderPath +
                ",if=none,id=redboxfolder,format=raw";

        arguments.emplace_back("-drive");
        arguments.emplace_back(sharedFolderDriveArgument);
        arguments.emplace_back("-device");

        if (diskInterface == "IDE") {
            arguments.emplace_back(
                    "ide-hd,drive=redboxfolder,bus=ide.0,unit=1"
            );
        } else {
            arguments.emplace_back(
                    "ide-hd,drive=redboxfolder,bus=ahci.2"
            );
        }

        LOGI(
                "QEMU VVFAT shared folder attached: %s",
                sharedFolderPath.c_str()
        );
    }

    /*
     * If an ISO was selected, expose it as a read-only ATAPI CD-ROM on
     * AHCI port 1. Keep the Windows VHD first in boot order so adding the
     * VirtIO driver ISO cannot accidentally replace the normal boot disk.
     */
    if (qemuIsoFd >= 0) {
        arguments.emplace_back("-drive");
        arguments.emplace_back(
                "file=/dev/fdset/2,if=none,id=redboxiso,media=cdrom,format=raw,readonly=on"
        );

        arguments.emplace_back("-device");

        if (diskInterface == "IDE") {
            arguments.emplace_back(
                    "ide-cd,drive=redboxiso,bus=ide.1,bootindex=2"
            );
        } else {
            // AHCI is also used for optical media when the main disk is VirtIO.
            arguments.emplace_back(
                    "ide-cd,drive=redboxiso,bus=ahci.1,bootindex=2"
            );
        }
    }

    /*
     * CD-ROM 2 is intended for virtio-win.iso or another driver/tools ISO.
     * Primary Windows installer remains bootindex=2; this disc is bootindex=3.
     */
    if (qemuDriverIsoFd >= 0) {
        arguments.emplace_back("-drive");
        arguments.emplace_back(
                "file=/dev/fdset/4,if=none,id=redboxdriveriso,media=cdrom,format=raw,readonly=on"
        );

        arguments.emplace_back("-device");

        if (diskInterface == "IDE") {
            arguments.emplace_back(
                    "ide-cd,drive=redboxdriveriso,bus=ide.1,unit=1,bootindex=3"
            );
        } else {
            arguments.emplace_back(
                    "ide-cd,drive=redboxdriveriso,bus=ahci.3,bootindex=3"
            );
        }
    }

    /*
     * BIOS / Guest Date.
     * This sets QEMU's guest RTC base date. "Default" leaves QEMU unchanged.
     */
    if (!biosDate.empty() && biosDate != "Default") {
        bool validBiosDate =
                biosDate.size() == 10 &&
                biosDate[4] == '-' &&
                biosDate[7] == '-';

        for (size_t i = 0; validBiosDate && i < biosDate.size(); ++i) {
            if (i == 4 || i == 7) {
                continue;
            }
            if (!std::isdigit(static_cast<unsigned char>(biosDate[i]))) {
                validBiosDate = false;
            }
        }

        if (validBiosDate) {
            arguments.emplace_back("-rtc");
            arguments.emplace_back("base=" + biosDate + "T00:00:00");
            LOGI("Guest RTC / BIOS date enabled: %s", biosDate.c_str());
        } else {
            LOGE("Ignoring invalid BIOS date '%s'; expected YYYY-MM-DD", biosDate.c_str());
        }
    }

    /*
     * Advanced custom QEMU parameters.
     *
     * Add these after RedBox's normal arguments so advanced users can access
     * QEMU options that do not yet have dedicated UI controls. No shell is
     * involved: the text is tokenized directly into argv.
     */
    if (!qemuParams.empty()) {
        const std::vector<std::string> customArguments =
                parseQemuParams(qemuParams);

        LOGI(
                "Custom QEMU parameters enabled: %zu argument(s)",
                customArguments.size()
        );

        for (const std::string& customArgument : customArguments) {
            if (!customArgument.empty()) {
                arguments.emplace_back(customArgument);
                LOGI("Custom QEMU argv: %s", customArgument.c_str());
            }
        }
    }

    std::vector<char*> argv;

    argv.reserve(
            arguments.size()
    );

    for (std::string& argument : arguments) {
        argv.push_back(
                const_cast<char*>(
                        argument.c_str()
                )
        );
    }

    int argc =
            static_cast<int>(
                    argv.size()
            );

    LOGI(
            "Calling redbox_qemu_run() Windows + optional ISO test with %d arguments...",
            argc
    );

    for (int i = 0; i < argc; i++) {
        LOGI(
                "argv[%d] = %s",
                i,
                argv[i]
        );
    }

    RedBoxStdioCapture stdioCapture;

    if (!startQemuStdioCapture(stdioCapture)) {
        if (qemuSharedDiskFd >= 0) {
            close(qemuSharedDiskFd);
        }

        if (sharedDiskFd >= 0) {
            closeAndroidFd(
                    env,
                    thiz,
                    sharedDiskFd
            );
        }

        if (qemuDriverIsoFd >= 0) {
            close(qemuDriverIsoFd);
        }
        if (driverIsoFd >= 0) {
            closeAndroidFd(env, thiz, driverIsoFd);
        }

        if (qemuIsoFd >= 0) {
            close(qemuIsoFd);
        }

        if (isoFd >= 0) {
            closeAndroidFd(
                    env,
                    thiz,
                    isoFd
            );
        }

        close(qemuRwFd);

        closeAndroidFd(
                env,
                thiz,
                diskFd
        );

        return env->NewStringUTF(
                "QEMU ADD-FD Test Failed: could not capture QEMU stderr"
        );
    }

    qemuInitialized.store(true);
    qemuRunning.store(true);

    int status =
            redBoxQemuRun(
                    argc,
                    argv.data()
            );

    qemuRunning.store(false);
    qemuInitialized.store(false);

    stopQemuStdioCapture(stdioCapture);

    LOGI(
            "redbox_qemu_run() returned status %d",
            status
    );

    if (sharedDiskFd >= 0) {
        closeAndroidFd(
                env,
                thiz,
                sharedDiskFd
        );
    }

    if (qemuDriverIsoFd >= 0) {
        close(qemuDriverIsoFd);
    }

    if (driverIsoFd >= 0) {
        closeAndroidFd(
                env,
                thiz,
                driverIsoFd
        );
    }

    if (isoFd >= 0) {
        closeAndroidFd(
                env,
                thiz,
                isoFd
        );
    }

    closeAndroidFd(
            env,
            thiz,
            diskFd
    );

    std::string result =
            "QEMU 11.1.1 Windows + Shared Storage Test Finished (status " +
            std::to_string(status) +
            ")";

    return env->NewStringUTF(
            result.c_str()
    );
}

/*
 * RedBox v0.1.1
 * QEMU isolated-process JNI bridge.
 *
 * QemuService runs in android:process=":qemu".
 *
 * The existing MainActivity implementation already operates on the JNI
 * 'thiz' object generically for get_fd(), close_fd(), getFilesDir(), and
 * prepareQemuFirmware(). Therefore the service JNI entry points can safely
 * forward to the existing implementation while supplying QemuService as
 * 'thiz'.
 */

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_rimvydop_redboxpcemulator_QemuService_nativeQemuStop(
        JNIEnv* env,
        jobject thiz
) {
    LOGI(
            "QemuService nativeQemuStop() bridge called"
    );

    return
            Java_com_rimvydop_redboxpcemulator_MainActivity_nativeQemuStop(
                    env,
                    thiz
            );
}


extern "C"
JNIEXPORT jboolean JNICALL
Java_com_rimvydop_redboxpcemulator_QemuService_nativeQemuMouseMove(
        JNIEnv* env,
        jobject thiz,
        jint deltaX,
        jint deltaY
) {
    return Java_com_rimvydop_redboxpcemulator_MainActivity_nativeQemuMouseMove(
            env,
            thiz,
            deltaX,
            deltaY
    );
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_rimvydop_redboxpcemulator_QemuService_nativeQemuMouseButton(
        JNIEnv* env,
        jobject thiz,
        jint button,
        jboolean down
) {
    return Java_com_rimvydop_redboxpcemulator_MainActivity_nativeQemuMouseButton(
            env,
            thiz,
            button,
            down
    );
}


extern "C"
JNIEXPORT jboolean JNICALL
Java_com_rimvydop_redboxpcemulator_QemuService_nativeQemuKeyboardKey(
        JNIEnv* env,
        jobject thiz,
        jint androidKeyCode,
        jboolean down
) {
    return Java_com_rimvydop_redboxpcemulator_MainActivity_nativeQemuKeyboardKey(
            env,
            thiz,
            androidKeyCode,
            down
    );
}


extern "C"
JNIEXPORT jstring JNICALL
Java_com_rimvydop_redboxpcemulator_QemuService_nativeQemuStart(
        JNIEnv* env,
        jobject thiz,
        jint ramMb,
        jint cpuCores,
        jstring diskUriJava,
        jstring diskImageNameJava,
        jstring isoUriJava,
        jstring driverIsoUriJava,
        jstring sharedDiskUriJava,
        jstring sharedDiskImageNameJava,
        jboolean sharedFolderEnabledJava,
        jstring cpuModelJava,
        jstring cpuFlagsJava,
        jint tcgCacheMb,
        jboolean multiThreadedTcg,
        jstring machineTypeJava,
        jstring diskInterfaceJava,
        jstring displayAdapterJava,
        jboolean networkEnabledJava,
        jstring networkAdapterJava,
        jstring networkModeJava,
        jstring qemuParamsJava,
        jstring biosDateJava,
        jstring soundCardJava
) {
    LOGI(
            "QemuService nativeQemuStart() bridge called in PID %d",
            getpid()
    );

    return
            Java_com_rimvydop_redboxpcemulator_MainActivity_nativeQemuStart(
                    env,
                    thiz,
                    ramMb,
                    cpuCores,
                    diskUriJava,
                    diskImageNameJava,
                    isoUriJava,
                    driverIsoUriJava,
                    sharedDiskUriJava,
                    sharedDiskImageNameJava,
                    sharedFolderEnabledJava,
                    cpuModelJava,
                    cpuFlagsJava,
                    tcgCacheMb,
                    multiThreadedTcg,
                    machineTypeJava,
                    diskInterfaceJava,
                    displayAdapterJava,
                    networkEnabledJava,
                    networkAdapterJava,
                    networkModeJava,
                    qemuParamsJava,
                    biosDateJava,
                    soundCardJava
            );
}
